package fr.lacaleche.pipe.bukkit.tabs.nms.enums;

import fr.lacaleche.pipe.bukkit.modules.nms.interfaces.enums.IStorageMethods;

public enum TabStorageMethods implements IStorageMethods {

    PCB_PLAYER_INFO_DATA$GET_PROFILE,
    SCOREBOARD_TEAMS$GET_PLAYERS,
    SCOREBOARD_TEAMS$SET_ALLOW_FRIENDLY_FIRE,
    SCOREBOARD_TEAMS$SET_CAN_SEE_FRIENDLY_INVISIBILES,
    SCOREBOARD_TEAMS$SET_PREFIX,
    SCOREBOARD_TEAMS$SET_SUFFIX,
    SCOREBOARD_TEAMS$SET_NAME_TAG_VISIBILITY,
    SCOREBOARD_TEAMS$SET_COLLISION_RULE,
    PACKET_CLIENTBOUNT_SET_PLAYER_TEAM$CREATE_ADD_OR_MODIFY_PACKET,
    PACKET_CLIENTBOUNT_SET_PLAYER_TEAM$CREATE_REMOVE_PACKET,

}
