package fr.lacaleche.pipe.bukkit.modules.nms.enums;

import fr.lacaleche.pipe.bukkit.modules.nms.interfaces.enums.IStorageConstructor;

public enum StorageConstructor implements IStorageConstructor {

    PACKET_PLAY_OUT_SPAWN_ENTITY_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_DESTROY_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_METADATA_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_TELEPORT_CONSTRUCTOR,
    PACKET_PLAY_OUT_REL_ENTITY_MOVE_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_LOOK_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_HEAD_ROTATION_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_VELOCITY_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_EQUIPMENT_CONSTRUCTOR,
    PACKET_PLAY_OUT_OPEN_SCREEN_CONSTRUCTOR,
    ADVENTURE_COMPONENT_CONSTRUCTOR,
    VEC_3D_XYZ_CONSTRUCTOR,
    BLOCK_POSITION_XYZ_CONSTRUCTOR,
    CHUNK_COORD_INT_PAIR_BLOCK_POSITION_CONSTRUCTOR,

}