package fr.lacaleche.pipe.bukkit.modules.nms.enums;

import fr.lacaleche.pipe.bukkit.modules.nms.interfaces.enums.IStorageClass;

public enum StorageClass implements IStorageClass {

    CRAFT_WORLD,
    WORLD,
    ENTITY,
    ENTITY_PLAYER,
    DATA_WATCHER,
    DATA_WATCHER$ITEM,
    DATA_WATCHER_OBJECT,
    ENTITY_LIVING,
    ENTITY_INSENTIENT,
    EQUIPMENT_SLOT,
    ITEM_STACK,
    NETWORK_MANAGER,
    PLAYER_CONNECTION,
    PACKET,
    PACKET_PLAY_OUT_SPAWN_ENTITY,
    PACKET_PLAY_OUT_ENTITY_DESTROY,
    PACKET_PLAY_OUT_ENTITY_METADATA,
    PACKET_PLAY_OUT_ENTITY_TELEPORT,
    PACKET_PLAY_OUT_REL_ENTITY_MOVE,
    PACKET_PLAY_OUT_ENTITY_LOOK,
    PACKET_PLAY_OUT_ENTITY_HEAD_ROTATION,
    PACKET_PLAY_OUT_ENTITY_VELOCITY,
    PACKET_PLAY_OUT_ENTITY_EQUIPMENT,
    ADVENTURE_COMPONENT,
    VEC_3D,
    BLOCK_POSITION,
    CHUNK_COORD_INT_PAIR,
    SECTION_POSITION

}
