package fr.lacaleche.pipe.bukkit.modules.nms.enums;

public enum StorageConstructor {

    PACKET_PLAY_OUT_SPAWN_ENTITY_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_DESTROY_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_METADATA_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_TELEPORT_CONSTRUCTOR,
    PACKET_PLAY_OUT_REL_ENTITY_MOVE_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_LOOK_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_HEAD_ROTATION_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_VELOCITY_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_EQUIPMENT_CONSTRUCTOR,
    PACKET_CLIENTBOUND_PLAYER_INFO_UPDATE_CONSTRUCTOR,
    PCB_PLAYER_INFO_DATA_CONSTRUCTOR,
    ADVENTURE_COMPONENT_CONSTRUCTOR,

}