package fr.lacaleche.pipe.bukkit.modules.nms.enums;

public enum StorageMethods {

    GET_DATA_WATCHER,
    PACK_DIRTY,
    GET_ID,
    SET_LOCATION,
    SET_INVISIBLE,
    SET_GLOWING,
    START_RIDING,
    STOP_RIDING,
    GET_PASSENGERS,
    SET_CAMERA,
    TICK,
    AI_STEP,
    SET_NO_GRAVITY,
    IS_NO_GRAVITY,
    SET_NO_AI,
    IS_NO_AI,
    SET_CUSTOM_NAME,
    SET_CUSTOM_NAME_VISIBLE,
    SET_ITEM_SLOT,
    PCB_PLAYER_INFO_DATA$GET_PROFILE,
    ADVENTURE_COMPONENT$GET_COMPONENT,


}
