package fr.lacaleche.pipe.bukkit.modules.nms.enums;

public enum StorageConstructor {

    PACKET_PLAY_OUT_SPAWN_ENTITY_LIVING_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_DESTROY_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_METADATA_CONSTRUCTOR,
    PACKET_PLAY_OUT_ENTITY_TELEPORT_CONSTRUCTOR

}
