package fr.lacaleche.pipe.bukkit.modules.nms.enums;

public enum StorageClass {

    CRAFT_WORLD,
    WORLD,
    ENTITY,
    ENTITY_PLAYER,
    DATA_WATCHER,
    ENTITY_LIVING,
    ENTITY_INSENTIENT,
    EQUIPMENT_SLOT,
    ITEM_STACK,
    NETWORK_MANAGER,
    PLAYER_CONNECTION,
    REMOTE_CHAT_SESSION_DATA,
    PACKET_PLAY_OUT_SPAWN_ENTITY,
    PACKET_PLAY_OUT_ENTITY_DESTROY,
    PACKET_PLAY_OUT_ENTITY_METADATA,
    PACKET_PLAY_OUT_ENTITY_TELEPORT,
    PACKET_PLAY_OUT_REL_ENTITY_MOVE,
    PACKET_PLAY_OUT_ENTITY_LOOK,
    PACKET_PLAY_OUT_ENTITY_HEAD_ROTATION,
    PACKET_PLAY_OUT_ENTITY_VELOCITY,
    PACKET_PLAY_OUT_ENTITY_EQUIPMENT,
    PACKET_CLIENTBOUND_PLAYER_INFO_UPDATE,
    PCB_PLAYER_INFO_DATA,
    PCB_PLAYER_INFO_ACTION,
    ADVENTURE_COMPONENT

}
